/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    404: typeof import('./resources/js/components/errors/404.vue')['default']
    AlertBox: typeof import('./resources/js/components/ui/AlertBox.vue')['default']
    AppButton: typeof import('./resources/js/components/ui/AppButton.vue')['default']
    AppCard: typeof import('./resources/js/components/ui/AppCard.vue')['default']
    AppInput: typeof import('./resources/js/components/ui/AppInput.vue')['default']
    AppNavbar: typeof import('./resources/js/components/layouts/AppNavbar.vue')['default']
    Auth: typeof import('./resources/js/layouts/auth.vue')['default']
    AuthLayout: typeof import('./resources/js/components/layouts/AuthLayout.vue')['default']
    Default: typeof import('./resources/js/layouts/default.vue')['default']
    ProfileField: typeof import('./resources/js/components/ProfileField.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatCard: typeof import('./resources/js/components/ui/StatCard.vue')['default']
  }
}
